import type { Metadata } from "next";
import "./css/globals.css";
import "./css/animation.css";
import "./css/fonts.css";
import "./css/util.css";
import AnimatePresenceWrapper from "@/components/animation/AnimatePresenceWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-gray-300 dark:bg-flat-black"}>{children}</body>
    </html>
  );
}
